:: Generated by: https://github.com/swagger-api/swagger-codegen.git
::

@echo off

dotnet restore SvarOMatic.Backend
dotnet build SvarOMatic.Backend
echo Now, run the following to start the project: dotnet run -p SvarOMatic.Backend.csproj --launch-profile web.
echo.
